name: BuildMacos

on:
  push:
    branches: [ "main" ]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: cargo build -p eusb --verbose
#      - name: Run tests
#        run: cargo test --verbose
