name: BuildAndroid

on:
  push:
    branches: [ "main" ]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b
          local-cache: true
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: aarch64-linux-android
          components: rustfmt, clippy
      - name: Setup Cargo-ndk
        run: cargo install cargo-ndk
      - name: Build
        run: cargo ndk -t arm64-v8a -t arm64-v8a build -p eusb --verbose
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
#      - name: Run tests
#        run: cargo test --verbose
